[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
unreadable_literal = "allow"
must_use_candidate = "allow"
std_instead_of_core = "warn"
std_instead_of_alloc = "warn"
alloc_instead_of_core = "warn"
float_arithmetic = "warn"

[workspace.lints.rust]
missing_debug_implementations = "warn"

[workspace.dependencies]
lunode-crypto = { path = "crates/lunode-crypto" }
lunode-primitives = { path = "crates/lunode-primitives" }
proptest = "1.11.0"

[workspace.package]
license = "MIT"
publish = false
